import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js boilerplate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='text-xl text-center text-red-600'>
        Next.js with TypeScript + TailwindCSS
      </div>
    </div>
  );
};

export default Home;
